<?php

<<<<<<<< HEAD:var/cache/dev/ContainerQ5su9NF/getReservation2Service.php
namespace ContainerQ5su9NF;

========
namespace ContainerNSRiD8R;
>>>>>>>> 22706224e6831c1c2fb6365639649c394e2f61b7:var/cache/dev/ContainerNSRiD8R/getReservation2Service.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h9c0uBq.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h9c0uBq": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".');
    }
}
