<?php

namespace ContainerXcE98m6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_65t9AJdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.65t9AJd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.65t9AJd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entreeSortie' => ['privates', '.errored..service_locator.65t9AJd.App\\Entity\\EntreeSortie', NULL, 'Cannot autowire service ".service_locator.65t9AJd": it needs an instance of "App\\Entity\\EntreeSortie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entreeSortie' => 'App\\Entity\\EntreeSortie',
        ]);
    }
}
