<?php

<<<<<<<< HEAD:var/cache/dev/ContainerPCUOW1n/getReservationService.php
namespace ContainerPCUOW1n;

========
namespace ContainerPdUOnCs;
>>>>>>>> 4e6b7b2fd64ebad93ea245379d93b8ad6abb4679:var/cache/dev/ContainerPdUOnCs/getReservationService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.doLz9ae.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.doLz9ae": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".');
    }
}
