<?php

namespace ContainerOPu3HQ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wjw_XiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._Wjw.xi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._Wjw.xi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'réservation' => ['privates', '.errored..service_locator._Wjw.xi.App\\Entity\\Réservation', NULL, 'Cannot autowire service ".service_locator._Wjw.xi": it needs an instance of "App\\Entity\\Réservation" but this type has been excluded in "config/services.yaml".'],
            'réservationRepository' => ['privates', 'App\\Repository\\RéservationRepository', 'getRéservationRepositoryService', true],
        ], [
            'réservation' => 'App\\Entity\\Réservation',
            'réservationRepository' => 'App\\Repository\\RéservationRepository',
        ]);
    }
}
