<?php

namespace ContainerOPu3HQ4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I6HASp6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I6HASp6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I6HASp6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Controller\\PaiementController::delete' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController::edit' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController::index' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController::new' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController::show' => ['privates', '.service_locator.W6WaZsJ', 'get_ServiceLocator_W6WaZsJService', true],
            'App\\Controller\\RéservationController::delete' => ['privates', '.service_locator._Wjw.xi', 'get_ServiceLocator_Wjw_XiService', true],
            'App\\Controller\\RéservationController::edit' => ['privates', '.service_locator._Wjw.xi', 'get_ServiceLocator_Wjw_XiService', true],
            'App\\Controller\\RéservationController::index' => ['privates', '.service_locator.ZHjtxDp', 'get_ServiceLocator_ZHjtxDpService', true],
            'App\\Controller\\RéservationController::new' => ['privates', '.service_locator.ZHjtxDp', 'get_ServiceLocator_ZHjtxDpService', true],
            'App\\Controller\\RéservationController::show' => ['privates', '.service_locator.T.cCDjl', 'get_ServiceLocator_T_CCDjlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Controller\\PaiementController:delete' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController:edit' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController:index' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController:new' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController:show' => ['privates', '.service_locator.W6WaZsJ', 'get_ServiceLocator_W6WaZsJService', true],
            'App\\Controller\\RéservationController:delete' => ['privates', '.service_locator._Wjw.xi', 'get_ServiceLocator_Wjw_XiService', true],
            'App\\Controller\\RéservationController:edit' => ['privates', '.service_locator._Wjw.xi', 'get_ServiceLocator_Wjw_XiService', true],
            'App\\Controller\\RéservationController:index' => ['privates', '.service_locator.ZHjtxDp', 'get_ServiceLocator_ZHjtxDpService', true],
            'App\\Controller\\RéservationController:new' => ['privates', '.service_locator.ZHjtxDp', 'get_ServiceLocator_ZHjtxDpService', true],
            'App\\Controller\\RéservationController:show' => ['privates', '.service_locator.T.cCDjl', 'get_ServiceLocator_T_CCDjlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\PaiementController::delete' => '?',
            'App\\Controller\\PaiementController::edit' => '?',
            'App\\Controller\\PaiementController::index' => '?',
            'App\\Controller\\PaiementController::new' => '?',
            'App\\Controller\\PaiementController::show' => '?',
            'App\\Controller\\RéservationController::delete' => '?',
            'App\\Controller\\RéservationController::edit' => '?',
            'App\\Controller\\RéservationController::index' => '?',
            'App\\Controller\\RéservationController::new' => '?',
            'App\\Controller\\RéservationController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\PaiementController:delete' => '?',
            'App\\Controller\\PaiementController:edit' => '?',
            'App\\Controller\\PaiementController:index' => '?',
            'App\\Controller\\PaiementController:new' => '?',
            'App\\Controller\\PaiementController:show' => '?',
            'App\\Controller\\RéservationController:delete' => '?',
            'App\\Controller\\RéservationController:edit' => '?',
            'App\\Controller\\RéservationController:index' => '?',
            'App\\Controller\\RéservationController:new' => '?',
            'App\\Controller\\RéservationController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
