<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUsOJn88\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUsOJn88/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUsOJn88.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUsOJn88\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerUsOJn88\App_KernelProdContainer([
    'container.build_hash' => 'UsOJn88',
    'container.build_id' => 'a02fb0c0',
    'container.build_time' => 1680990017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUsOJn88');
