<?php

namespace ContainerUsOJn88;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIParkControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\IParkController' shared autowired service.
     *
     * @return \App\Controller\IParkController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\IParkController'] = $instance = new \App\Controller\IParkController();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
        ]))->withContext('App\\Controller\\IParkController', $container));

        return $instance;
    }
}
