<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\Persistence\Proxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Paiement' => [parent::class, 'Paiement', null],
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'client' => [parent::class, 'client', null],
        "\0".parent::class."\0".'date_reservation' => [parent::class, 'date_reservation', null],
        "\0".parent::class."\0".'entreeSortie' => [parent::class, 'entreeSortie', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'parking' => [parent::class, 'parking', null],
        "\0".parent::class."\0".'place' => [parent::class, 'place', null],
        "\0".parent::class."\0".'type_vehicule' => [parent::class, 'type_vehicule', null],
        'Paiement' => [parent::class, 'Paiement', null],
        'adresse' => [parent::class, 'adresse', null],
        'client' => [parent::class, 'client', null],
        'date_reservation' => [parent::class, 'date_reservation', null],
        'entreeSortie' => [parent::class, 'entreeSortie', null],
        'id' => [parent::class, 'id', null],
        'parking' => [parent::class, 'parking', null],
        'place' => [parent::class, 'place', null],
        'type_vehicule' => [parent::class, 'type_vehicule', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'adresse' => true,
            "\0".parent::class."\0".'id' => true,
            "\0".parent::class."\0".'parking' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
