<?php

namespace ContainerLEQXEcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y0SKFZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y0SKF_Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y0SKF_Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
