<?php

namespace ContainerGzG02IM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QXTG4AService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._QXTG4A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._QXTG4A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entreeSortieRepository' => ['privates', 'App\\Repository\\EntreeSortieRepository', 'getEntreeSortieRepositoryService', true],
        ], [
            'entreeSortieRepository' => 'App\\Repository\\EntreeSortieRepository',
        ]);
    }
}
