<?php

namespace ContainerGzG02IM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DSUTG_MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dSUTG.M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dSUTG.M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'place' => ['privates', '.errored..service_locator.dSUTG.M.App\\Entity\\Place', NULL, 'Cannot autowire service ".service_locator.dSUTG.M": it needs an instance of "App\\Entity\\Place" but this type has been excluded in "config/services.yaml".'],
        ], [
            'place' => 'App\\Entity\\Place',
        ]);
    }
}
