<?php

namespace ContainerIEy2me8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGqhVIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tGqhVI_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tGqhVI_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'place' => ['privates', '.errored..service_locator.tGqhVI_.App\\Entity\\Place', NULL, 'Cannot autowire service ".service_locator.tGqhVI_": it needs an instance of "App\\Entity\\Place" but this type has been excluded in "config/services.yaml".'],
            'placeRepository' => ['privates', 'App\\Repository\\PlaceRepository', 'getPlaceRepositoryService', true],
        ], [
            'place' => 'App\\Entity\\Place',
            'placeRepository' => 'App\\Repository\\PlaceRepository',
        ]);
    }
}
