<?php

namespace ContainerIEy2me8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntreeSortieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.65t9AJd.App\Entity\EntreeSortie' shared service.
     *
     * @return \App\Entity\EntreeSortie
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.65t9AJd": it needs an instance of "App\\Entity\\EntreeSortie" but this type has been excluded in "config/services.yaml".');
    }
}
