<?php

namespace ContainerTToF2sG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PMazzvAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pMazzvA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pMazzvA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PaiementController::delete' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController::edit' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController::index' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController::new' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController::show' => ['privates', '.service_locator.W6WaZsJ', 'get_ServiceLocator_W6WaZsJService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.v.Ev_hT', 'get_ServiceLocator_V_EvHTService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController::generatePdfReservation' => ['privates', '.service_locator.Wpr_aEu', 'get_ServiceLocator_WprAEuService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController::step1edit' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController::step2edit' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController::step2new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PaiementController:delete' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController:edit' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController:index' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController:new' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController:show' => ['privates', '.service_locator.W6WaZsJ', 'get_ServiceLocator_W6WaZsJService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.v.Ev_hT', 'get_ServiceLocator_V_EvHTService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController:generatePdfReservation' => ['privates', '.service_locator.Wpr_aEu', 'get_ServiceLocator_WprAEuService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController:step1edit' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController:step2edit' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController:step2new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PaiementController::delete' => '?',
            'App\\Controller\\PaiementController::edit' => '?',
            'App\\Controller\\PaiementController::index' => '?',
            'App\\Controller\\PaiementController::new' => '?',
            'App\\Controller\\PaiementController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\ReservationController::generatePdfReservation' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Controller\\ReservationController::step1edit' => '?',
            'App\\Controller\\ReservationController::step2edit' => '?',
            'App\\Controller\\ReservationController::step2new' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PaiementController:delete' => '?',
            'App\\Controller\\PaiementController:edit' => '?',
            'App\\Controller\\PaiementController:index' => '?',
            'App\\Controller\\PaiementController:new' => '?',
            'App\\Controller\\PaiementController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\ReservationController:generatePdfReservation' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'App\\Controller\\ReservationController:step1edit' => '?',
            'App\\Controller\\ReservationController:step2edit' => '?',
            'App\\Controller\\ReservationController:step2new' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
