<?php

namespace ContainerXpgfqZe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H_FCutFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h.FCutF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h.FCutF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ClientController::delete' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController::edit' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController::index' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController::new' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController::show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Controller\\PaiementController::delete' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController::edit' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController::index' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController::new' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController::show' => ['privates', '.service_locator.W6WaZsJ', 'get_ServiceLocator_W6WaZsJService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController::edit' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController::index' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController::new' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClientController:delete' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController:edit' => ['privates', '.service_locator.T1NedXT', 'get_ServiceLocator_T1NedXTService', true],
            'App\\Controller\\ClientController:index' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController:new' => ['privates', '.service_locator.sUhGGzt', 'get_ServiceLocator_SUhGGztService', true],
            'App\\Controller\\ClientController:show' => ['privates', '.service_locator.lTbvCHw', 'get_ServiceLocator_LTbvCHwService', true],
            'App\\Controller\\PaiementController:delete' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController:edit' => ['privates', '.service_locator.bSws.pL', 'get_ServiceLocator_BSws_PLService', true],
            'App\\Controller\\PaiementController:index' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController:new' => ['privates', '.service_locator.69GazA_', 'get_ServiceLocator_69GazAService', true],
            'App\\Controller\\PaiementController:show' => ['privates', '.service_locator.W6WaZsJ', 'get_ServiceLocator_W6WaZsJService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController:edit' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController:index' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController:new' => ['privates', '.service_locator.caJHb8S', 'get_ServiceLocator_CaJHb8SService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClientController::delete' => '?',
            'App\\Controller\\ClientController::edit' => '?',
            'App\\Controller\\ClientController::index' => '?',
            'App\\Controller\\ClientController::new' => '?',
            'App\\Controller\\ClientController::show' => '?',
            'App\\Controller\\PaiementController::delete' => '?',
            'App\\Controller\\PaiementController::edit' => '?',
            'App\\Controller\\PaiementController::index' => '?',
            'App\\Controller\\PaiementController::new' => '?',
            'App\\Controller\\PaiementController::show' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\ReservationController::edit' => '?',
            'App\\Controller\\ReservationController::index' => '?',
            'App\\Controller\\ReservationController::new' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClientController:delete' => '?',
            'App\\Controller\\ClientController:edit' => '?',
            'App\\Controller\\ClientController:index' => '?',
            'App\\Controller\\ClientController:new' => '?',
            'App\\Controller\\ClientController:show' => '?',
            'App\\Controller\\PaiementController:delete' => '?',
            'App\\Controller\\PaiementController:edit' => '?',
            'App\\Controller\\PaiementController:index' => '?',
            'App\\Controller\\PaiementController:new' => '?',
            'App\\Controller\\PaiementController:show' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\ReservationController:edit' => '?',
            'App\\Controller\\ReservationController:index' => '?',
            'App\\Controller\\ReservationController:new' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
