<?php

namespace ContainerXpgfqZe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BSws_PLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bSws.pL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bSws.pL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paiement' => ['privates', '.errored..service_locator.bSws.pL.App\\Entity\\Paiement', NULL, 'Cannot autowire service ".service_locator.bSws.pL": it needs an instance of "App\\Entity\\Paiement" but this type has been excluded in "config/services.yaml".'],
            'paiementRepository' => ['privates', 'App\\Repository\\PaiementRepository', 'getPaiementRepositoryService', true],
        ], [
            'paiement' => 'App\\Entity\\Paiement',
            'paiementRepository' => 'App\\Repository\\PaiementRepository',
        ]);
    }
}
