<?php

namespace ContainerCqqsLtT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LrlPtrSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LrlPtrS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LrlPtrS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.JIwYVTk', 'get_ServiceLocator_JIwYVTkService', true],
            'App\\Controller\\ReservationController::delete' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController::generatePdfReservation' => ['privates', '.service_locator.Wpr_aEu', 'get_ServiceLocator_WprAEuService', true],
            'App\\Controller\\ReservationController::show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController::step1edit' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController::step1new' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ReservationController::step2edit' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController::step2new' => ['privates', '.service_locator.OHLk6_9', 'get_ServiceLocator_OHLk69Service', true],
            'App\\Controller\\ReservationController::step3new' => ['privates', '.service_locator.OHLk6_9', 'get_ServiceLocator_OHLk69Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.JIwYVTk', 'get_ServiceLocator_JIwYVTkService', true],
            'App\\Controller\\ReservationController:delete' => ['privates', '.service_locator.doLz9ae', 'get_ServiceLocator_DoLz9aeService', true],
            'App\\Controller\\ReservationController:generatePdfReservation' => ['privates', '.service_locator.Wpr_aEu', 'get_ServiceLocator_WprAEuService', true],
            'App\\Controller\\ReservationController:show' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController:step1edit' => ['privates', '.service_locator.h9c0uBq', 'get_ServiceLocator_H9c0uBqService', true],
            'App\\Controller\\ReservationController:step1new' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ReservationController:step2edit' => ['privates', '.service_locator.rNyJSA0', 'get_ServiceLocator_RNyJSA0Service', true],
            'App\\Controller\\ReservationController:step2new' => ['privates', '.service_locator.OHLk6_9', 'get_ServiceLocator_OHLk69Service', true],
            'App\\Controller\\ReservationController:step3new' => ['privates', '.service_locator.OHLk6_9', 'get_ServiceLocator_OHLk69Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservationController::delete' => '?',
            'App\\Controller\\ReservationController::generatePdfReservation' => '?',
            'App\\Controller\\ReservationController::show' => '?',
            'App\\Controller\\ReservationController::step1edit' => '?',
            'App\\Controller\\ReservationController::step1new' => '?',
            'App\\Controller\\ReservationController::step2edit' => '?',
            'App\\Controller\\ReservationController::step2new' => '?',
            'App\\Controller\\ReservationController::step3new' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservationController:delete' => '?',
            'App\\Controller\\ReservationController:generatePdfReservation' => '?',
            'App\\Controller\\ReservationController:show' => '?',
            'App\\Controller\\ReservationController:step1edit' => '?',
            'App\\Controller\\ReservationController:step1new' => '?',
            'App\\Controller\\ReservationController:step2edit' => '?',
            'App\\Controller\\ReservationController:step2new' => '?',
            'App\\Controller\\ReservationController:step3new' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
