<?php

namespace ContainerJ8Uyu4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5eJHeVOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5eJHeVO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5eJHeVO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pdf' => ['privates', '.errored..service_locator.5eJHeVO.Knp\\Snappy\\Pdf', NULL, 'Cannot autowire service ".service_locator.5eJHeVO": it references class "Knp\\Snappy\\Pdf" but no such service exists.'],
        ], [
            'pdf' => 'Knp\\Snappy\\Pdf',
        ]);
    }
}
