<?php

namespace ContainerJ8Uyu4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YZoFQ81Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yZoFQ81' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yZoFQ81'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'parking' => ['privates', '.errored..service_locator.yZoFQ81.App\\Entity\\Parking', NULL, 'Cannot autowire service ".service_locator.yZoFQ81": it needs an instance of "App\\Entity\\Parking" but this type has been excluded in "config/services.yaml".'],
        ], [
            'parking' => 'App\\Entity\\Parking',
        ]);
    }
}
