<?php

namespace ContainerJ8Uyu4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dSUTG.M.App\Entity\Place' shared service.
     *
     * @return \App\Entity\Place
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dSUTG.M": it needs an instance of "App\\Entity\\Place" but this type has been excluded in "config/services.yaml".');
    }
}
