<?php

namespace ContainerJ8Uyu4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParkingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Og9uKc7.App\Entity\Parking' shared service.
     *
     * @return \App\Entity\Parking
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Og9uKc7": it needs an instance of "App\\Entity\\Parking" but this type has been excluded in "config/services.yaml".');
    }
}
