<?php

namespace ContainerJ8Uyu4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5eJHeVO.Knp\Snappy\Pdf' shared service.
     *
     * @return \Knp\Snappy\Pdf
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5eJHeVO": it references class "Knp\\Snappy\\Pdf" but no such service exists.');
    }
}
