<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRu1dvg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRu1dvg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRu1dvg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRu1dvg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHRu1dvg\App_KernelDevDebugContainer([
    'container.build_hash' => 'HRu1dvg',
    'container.build_id' => 'f064fedf',
    'container.build_time' => 1680936746,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRu1dvg');
