<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZMepjc5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZMepjc5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZMepjc5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZMepjc5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZMepjc5\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZMepjc5',
    'container.build_id' => '41f9658a',
    'container.build_time' => 1681080897,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZMepjc5');
