<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_client_index' => [[], ['_controller' => 'App\\Controller\\ClientController::index'], [], [['text', '/client/']], [], [], []],
    'app_client_new' => [[], ['_controller' => 'App\\Controller\\ClientController::new'], [], [['text', '/client/new']], [], [], []],
    'app_client_show' => [['id'], ['_controller' => 'App\\Controller\\ClientController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], [], []],
    'app_client_edit' => [['id'], ['_controller' => 'App\\Controller\\ClientController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], [], []],
    'app_client_delete' => [['id'], ['_controller' => 'App\\Controller\\ClientController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/client']], [], [], []],
    'app_i_park' => [[], ['_controller' => 'App\\Controller\\IParkController::index'], [], [['text', '/ipark']], [], [], []],
    'app_paiement_index' => [[], ['_controller' => 'App\\Controller\\PaiementController::index'], [], [['text', '/paiement/']], [], [], []],
    'app_paiement_new' => [[], ['_controller' => 'App\\Controller\\PaiementController::new'], [], [['text', '/paiement/new']], [], [], []],
    'app_paiement_show' => [['id'], ['_controller' => 'App\\Controller\\PaiementController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/paiement']], [], [], []],
    'app_paiement_edit' => [['id'], ['_controller' => 'App\\Controller\\PaiementController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/paiement']], [], [], []],
    'app_paiement_delete' => [['id'], ['_controller' => 'App\\Controller\\PaiementController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/paiement']], [], [], []],
    'app_reservation_index' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/reservation/']], [], [], []],
    'app_reservation_new' => [[], ['_controller' => 'App\\Controller\\ReservationController::new'], [], [['text', '/reservation/new']], [], [], []],
    'app_reservation_show' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reservation']], [], [], []],
    'app_reservation_edit' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/reservation']], [], [], []],
    'app_reservation_delete' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/reservation']], [], [], []],
];
